server:
  servlet:
    context-path: /api
  port: 8002

spring:
  application:
    name: client-service

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE
    com.logging.presentation: DEBUG